sudo: required
services:
  - docker

before_install:
  - docker build -t shahalw/react-test -f ./client/Dockerfile.dev ./client
  # For more tests add more builds here
  
script:
  - docker run -e CI=true shahalw/react-test npm test -- --coverage
  # For more tests add more scripts here

after_success:
  - docker build -t shahalw/multi-client ./client
  - docker build -t shahalw/multi-nginx ./nginx
  - docker build -t shahalw/multi-server ./server
  - docker build -t shahalw/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them into docker hub
  - docker push shahalw/multi-client
  - docker push shahalw/multi-nginx
  - docker push shahalw/multi-server
  - docker push shahalw/multi-worker